version: '3.3'
services:
  post_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - comment_db
          - post_db
    environment:
       - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
  ui:
    image: ${USERNAME}/ui
    environment:
          - POST_SERVICE_HOST=post
          - POST_SERVICE_PORT=5000
          - COMMENT_SERVICE_HOST=comment
          - COMMENT_SERVICE_PORT=9292
    ports:
          - "9292:9292"
    depends_on:
          - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
        - front_net
    environment:
        - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}

  post:
    image: ${USER_NAME}/post:${POST_VERSION}
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    networks:
      - back_net
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
volumes:
  post_db:

networks:
  back_net:
          ipam:
                  driver: default
                  config:
                          - subnet: "10.0.2.0/24"
  front_net:
          ipam:
                  driver: default
                  config:
                          - subnet: "10.0.1.0/24"
